const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
function setup(){
 const elements={},requests=[],revoked=[],downloads=[],blobs=[],copied=[];let imageWidth=200,decoded='https://example.com/',fetchResult={ok:true,json:async()=>({checks:[{status:'completed'}],summary:'Evidence',verdict:'unknown'})};
 class E{constructor(tag='div'){this.tagName=tag;this.children=[];this.events={};this.style={setProperty(){}};this.classList={add(){},remove(){}};this.value='';this.checked=false;this.attrs={};this._text='';}set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}append(...items){this.children.push(...items);}appendChild(e){this.children.push(e);}replaceChildren(){this.children=[];this._text='';}addEventListener(k,f){this.events[k]=f;}setAttribute(k,v){this.attrs[k]=v;}removeAttribute(k){delete this.attrs[k];}remove(){}click(){if(this.tagName==='a')downloads.push(this.download);else return this.events.click?.();}querySelectorAll(){return this.children.filter(c=>c.tagName==='button');}getContext(){return {drawImage(){},getImageData:()=>({data:new Uint8ClampedArray(4)})};}}
 const node=id=>elements[id]||(elements[id]=new E());class U extends URL{static createObjectURL(b){blobs.push(b);return 'blob:'+blobs.length;}static revokeObjectURL(u){revoked.push(u);}}
 class I{constructor(){this.width=imageWidth;this.height=200;}set src(v){this.onload();}}
 const ctx={window:{addEventListener(){}},document:{getElementById:node,createElement:t=>new E(t),body:new E()},URL:U,Image:I,Blob,AbortController,Uint8ClampedArray,console,setInterval(){return 1;},clearInterval(){},setTimeout(){return 1;},clearTimeout(){},navigator:{clipboard:{writeText:async v=>copied.push(v)}},fetch:async(url,options)=>{requests.push({url,options});return fetchResult;},jsQR:()=>decoded===null?null:{data:decoded}};
 vm.createContext(ctx);for(const file of ['qr_payload.js','qr_workspace.js']){vm.runInContext(fs.readFileSync(__dirname+'/../static/'+file,'utf8'),ctx);ctx.QRPayload=ctx.window.QRPayload;}ctx.WebAssessmentUI={render(target,data){target.textContent=data.summary;}};ctx.window.QRWorkspace.init();
 return {api:ctx.window.QRWorkspace,node,requests,revoked,downloads,blobs,copied,setDecode(v){decoded=v;},setImageWidth(v){imageWidth=v;},setResponse(v){fetchResult=v;}};
}
(async()=>{
 let checks=0;const ok=(v,message)=>{assert.ok(v,message);checks++;};const s=setup();s.api.fileSelected({name:'qr.png',type:'image/png',size:200});await s.api.decodeAndScan();ok(s.requests.length===0,'decode never contacts API');ok(s.node('decoded-content').textContent==='https://example.com/');ok(!s.node('result-card').hidden);ok(s.node('qr-coverage').hidden,'no synthetic score before assessment');ok(s.revoked.length===1,'decode temporary URL revoked');
 await s.api.inspect();ok(s.requests.length===1);ok(JSON.parse(s.requests[0].options.body).include_provider===false);ok(s.node('qr-percent').textContent==='100%');ok(!s.node('scan-btn').disabled);
 s.node('include-provider').checked=true;s.setResponse({ok:false,json:async()=>({error:'Provider <not available>'})});await s.api.inspect();ok(s.node('error-msg').textContent==='Provider <not available>');ok(s.node('decoded-content').textContent==='https://example.com/','failed assessment preserves decode');ok(s.node('qr-coverage').hidden,'failed assessment cannot show stale coverage');ok(s.node('qr-brief').textContent.includes('attempted but no current assessment')); 
 s.setDecode(null);await s.api.decodeAndScan();ok(s.node('error-msg').textContent.includes('No readable QR'));ok(!s.node('scan-btn').disabled,'retry available');ok(s.node('result-card').hidden,'failed decode hides old result');
 s.setImageWidth(100000);await s.api.decodeAndScan();ok(s.node('error-msg').textContent.includes('16 megapixels'));
 s.api.fileSelected({name:'bad.txt',type:'text/plain',size:20});ok(s.node('scan-btn').disabled);ok(s.node('file-selected').hidden);
 s.api.renderTextResult('WIFI:S:PrivateNetwork;P:top-secret;;');ok(!s.node('decoded-content').textContent.includes('top-secret'));let buttons=s.node('action-buttons').children;buttons.find(b=>b.textContent==='Export JSON').click();ok(!(await s.blobs.at(-1).text()).includes('top-secret'));buttons.find(b=>b.textContent==='Reveal sensitive content').click();ok(s.node('decoded-content').textContent.includes('top-secret'));buttons=s.node('action-buttons').children;await buttons.find(b=>b.textContent==='Copy sensitive payload').click();ok(s.copied.at(-1).includes('top-secret'));buttons.find(b=>b.textContent==='Hide sensitive content').click();ok(!s.node('decoded-content').textContent.includes('top-secret'));
 s.api.reset();ok(s.node('decoded-content').textContent==='');ok(s.node('include-provider').checked===false);ok(s.node('result-card').hidden);ok(s.revoked.length>=2);
 console.log(`PASS: ${checks} QR workflow, explicit inspection, error recovery, privacy and cleanup assertions`);
})().catch(e=>{console.error(e);process.exitCode=1;});
