"""Frozen application baseline preceding the original empty revision.

Existing legacy tables are retained; missing columns require explicit repair.
"""
from alembic import op
import sqlalchemy as sa

revision = '0b21a5e798c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    actions = []
    def _table(name, *columns, **kwargs):
        actions.append(('table', name, columns, kwargs))
    def _index(name, table, columns, **kwargs):
        actions.append(('index', name, table, columns, kwargs))
# ### commands auto generated by Alembic - please adjust! ###
    _table('ioc_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('feed_type', sa.String(length=30), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval', sa.Integer(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('last_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    _table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _index(op.f('ix_log_entry_action'), 'log_entry', ['action'], unique=False)
    _index(op.f('ix_log_entry_timestamp'), 'log_entry', ['timestamp'], unique=False)
    _index(op.f('ix_log_entry_user_id'), 'log_entry', ['user_id'], unique=False)
    _table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('remaining_scans', sa.Integer(), nullable=True),
    sa.Column('scans_reset_date', sa.DateTime(), nullable=True),
    sa.Column('site_scan_remaining', sa.Integer(), nullable=True),
    sa.Column('file_scan_remaining', sa.Integer(), nullable=True),
    sa.Column('url_analyzer_remaining', sa.Integer(), nullable=True),
    sa.Column('email_check_remaining', sa.Integer(), nullable=True),
    sa.Column('ip_check_remaining', sa.Integer(), nullable=True),
    sa.Column('domain_lookup_remaining', sa.Integer(), nullable=True),
    sa.Column('ssl_check_remaining', sa.Integer(), nullable=True),
    sa.Column('qr_scan_remaining', sa.Integer(), nullable=True),
    sa.Column('subdomain_finder_remaining', sa.Integer(), nullable=True),
    sa.Column('password_check_remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    _table('ioc_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('ioc_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('threat_type', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('misp_event_id', sa.String(length=100), nullable=True),
    sa.Column('misp_attribute', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['ioc_source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value', 'ioc_type', name='uq_ioc_value_type')
    )
    _index('idx_ioc_active_severity', 'ioc_entry', ['is_active', 'severity'], unique=False)
    _index(op.f('ix_ioc_entry_ioc_type'), 'ioc_entry', ['ioc_type'], unique=False)
    _index(op.f('ix_ioc_entry_value'), 'ioc_entry', ['value'], unique=False)
    _table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('raw_report', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _table('scan_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('config_data', sa.Text(), nullable=False),
    sa.Column('zap_context', sa.Text(), nullable=True),
    sa.Column('zap_policy', sa.String(length=100), nullable=True),
    sa.Column('openvas_target_group', sa.String(length=100), nullable=True),
    sa.Column('openvas_task_config', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _index(op.f('ix_scan_configs_user_id'), 'scan_configs', ['user_id'], unique=False)
    _table('tip_feed_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_count', sa.Integer(), nullable=True),
    sa.Column('updated_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['ioc_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    _table('vulnerability_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_uuid', sa.String(length=64), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_vulnerabilities', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('high_count', sa.Integer(), nullable=True),
    sa.Column('medium_count', sa.Integer(), nullable=True),
    sa.Column('low_count', sa.Integer(), nullable=True),
    sa.Column('info_count', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('scan_duration', sa.Integer(), nullable=True),
    sa.Column('scan_progress', sa.Integer(), nullable=True),
    sa.Column('vulnerabilities_data', sa.Text(), nullable=True),
    sa.Column('scan_config', sa.Text(), nullable=True),
    sa.Column('scan_logs', sa.Text(), nullable=True),
    sa.Column('sources', sa.String(length=200), nullable=True),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('report_formats', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _index(op.f('ix_vulnerability_scans_scan_uuid'), 'vulnerability_scans', ['scan_uuid'], unique=True)
    _index(op.f('ix_vulnerability_scans_status'), 'vulnerability_scans', ['status'], unique=False)
    _index(op.f('ix_vulnerability_scans_user_id'), 'vulnerability_scans', ['user_id'], unique=False)
    _table('ioc_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=True),
    sa.Column('ioc_value', sa.String(length=512), nullable=False),
    sa.Column('ioc_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['ioc_entry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    _table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vuln_id', sa.String(length=100), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('affected_component', sa.String(length=200), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('proof_of_concept', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('plugin_id', sa.String(length=50), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), nullable=True),
    sa.Column('fixed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['vulnerability_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _index(op.f('ix_vulnerabilities_scan_id'), 'vulnerabilities', ['scan_id'], unique=False)
    _index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    _index(op.f('ix_vulnerabilities_vuln_id'), 'vulnerabilities', ['vuln_id'], unique=True)
    # ### end Alembic commands ###
    inspector = sa.inspect(op.get_bind())
    existing = set(inspector.get_table_names())
    # Validate all existing baseline tables before the first DDL operation.
    for action in actions:
        if action[0] == 'table' and action[1] in existing:
            required = {column.name for column in action[2] if isinstance(column, sa.Column)}
            actual = {column['name'] for column in inspector.get_columns(action[1])}
            if not required.issubset(actual):
                raise RuntimeError('Legacy schema has missing columns; repair a restored copy before migration.')
    for action in actions:
        if action[0] == 'table':
            _, name, columns, kwargs = action
            if name not in existing:
                op.create_table(name, *columns, **kwargs)
        else:
            _, name, table, columns, kwargs = action
            indexes = {index['name'] for index in sa.inspect(op.get_bind()).get_indexes(table)}
            if str(name) not in indexes:
                op.create_index(name, table, columns, **kwargs)


def downgrade():
    raise RuntimeError('Baseline downgrade is disabled; restore a verified backup instead.')
